---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "18:30"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependencies(github-actions): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "dependabot*"
      lint-actions:
        patterns:
          - "*/*-dependabot"
          - "*cspell*"
          - "super-linter*"
      pr-actions:
        patterns:
          - "*block-merge-conflicts"
          - "*pull-request*"
          - "*pr-labeler*"
          - "*version-increment"

  # Keep NuGet packages up to date
  - package-ecosystem: "nuget"
    directory: "/examples/MinimalWebApi"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependencies(nuget): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    # Force lock file regeneration
    rebase-strategy: auto
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
        update-types: ["minor", "patch"]
      testing:
        patterns:
          - "AwesomeAssertions*"
          - "coverlet*"
          - "FakeItEasy*"
          - "GitHubActionsTestLogger"
          - "xunit*"
        update-types: ["minor", "patch"]
      other-packages:
        patterns:
          - "Scalar.AspNetCore*"
        update-types: ["minor", "patch"]

  - package-ecosystem: "nuget"
    directory: "/examples/NugetPackages"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependencies(nuget): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    # Force lock file regeneration
    rebase-strategy: auto
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
        update-types: ["minor", "patch"]
      testing:
        patterns:
          - "AwesomeAssertions*"
          - "coverlet*"
          - "FakeItEasy*"
          - "GitHubActionsTestLogger"
          - "xunit*"
        update-types: ["minor", "patch"]
      other-packages:
        patterns:
          - "Scalar.AspNetCore*"
        update-types: ["minor", "patch"]
