---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "18:30"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "chore(github-actions): "
