name: github-tag-and-release

on:
  workflow_call:
    inputs:
      harden-runner-policy:
        description: "The egress policy for the Harden Runner step. Defaults to 'block'"
        required: false
        type: string
        default: "block"
      version:
        description: "Version number to tag and release (without the 'v' prefix)"
        required: true
        type: string
permissions:
  contents: read

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: ${{ inputs.harden-runner-policy }}
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            uploads.github.com:443

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ inputs.version }}"
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"

      - name: Github Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          generate_release_notes: true
          make_latest: true
