name: dependabot-approve-and-merge

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot-auto-approve-and-merge:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/_dependabot-auto-approve-and-merge.yml
    with:
      is-fork: ${{ github.event.repository.fork }}
      user-login: ${{ github.event.pull_request.user.login }}
      pr-url: ${{ github.event.pull_request.html_url }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
