name: dotnet-package-pr

on:
  workflow_call:
    inputs:
      harden-runner-policy:
        description: "The egress policy for the Harden Runner step. Defaults to 'block'"
        required: false
        type: string
        default: "block"
      working-directory:
        description: "The working directory for the job. Defaults to '.' which is the root of the repository. Do not include trailing '/'"
        required: false
        type: string
        default: "."
      os:
        description: The operating system to run non-matrix jobs on. e.g. "ubuntu-latest" or "windows-latest".
        required: false
        type: string
        default: ubuntu-latest
      dotnet-version-matrix:
        description: 'JSON array of dotnet-version/framework pairs. Must be on one line. eg ''[{ "dotnet-version": "9.0.x", "framework": "net9.0" }, { "dotnet-version": "10.0.x", "framework": "net10.0" }]'''
        required: false
        type: string
      dotnet-version:
        description: The dotnet version to run the non-matrix jobs with. e.g. "10.0.x".
        required: false
        type: string
        default: 10.0.x
      run-lint:
        required: false
        type: boolean
        default: false
      cspell-config:
        description: "Path to the cspell configuration file. Required to run spell-checking. eg '.cspell.json'"
        required: false
        type: string
      num-github-prerelease-packages-to-keep:
        description: "We cleanup github prerelease nuget packages. Configure how many to keep"
        type: number
        required: false
        default: 50
      codecov-slug:
        description: "Slug to upload code coverage results for Codecov. e.g. saan800/saansoft-correlationId"
        required: false
        type: string
      codecov-flag:
        description: "Flag to use for Codecov. e.g. unittests"
        required: false
        type: string
        default: unittests
    secrets:
      NUGET_API_KEY:
        description: "API key for nuget.org. Required if upload-to-nuget is true"
        required: false
      CODECOV_TOKEN:
        description: "Token for CodeCov. Required if codecov-slug is set"
        required: false

permissions:
  actions: read
  contents: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  ci-cd:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/_dotnet-build-test-pack-publish-nuget.yml
    with:
      harden-runner-policy: ${{ inputs.harden-runner-policy }}
      working-directory: ${{ inputs.working-directory }}
      os: ${{ inputs.os }}
      dotnet-version-matrix: ${{ inputs.dotnet-version-matrix }}
      dotnet-version: ${{ inputs.dotnet-version }}
      num-github-prerelease-packages-to-keep: ${{ inputs.num-github-prerelease-packages-to-keep }}
      codecov-slug: ${{ inputs.codecov-slug }}
      codecov-flag: ${{ inputs.codecov-flag }}
      is-release-branch: false
      force-release: false
    secrets: inherit

  pr-labels:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/_pr-labeler.yml
    with:
      harden-runner-policy: ${{ inputs.harden-runner-policy }}
    secrets: inherit

  pr-lint:
    permissions:
      contents: read
    uses: ./.github/workflows/_pr-lint.yml
    with:
      harden-runner-policy: ${{ inputs.harden-runner-policy }}
      run-lint: ${{ inputs.run-lint }}
      cspell-config: ${{ inputs.cspell-config }}
    secrets: inherit

  dependency-review:
    permissions:
      contents: read
    uses: ./.github/workflows/_dependency-review.yml
    with:
      harden-runner-policy: ${{ inputs.harden-runner-policy }}
