name: example-nuget-packages

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:   # 👈 allow manual trigger here too
    inputs:
      force-release:
        description: "Force a release regardless of PR labels"
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  packages: write

jobs:
  ci-cd:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/_dotnet-build-test-pack-publish-nuget.yml
    with:
      working-directory: "./examples/NugetPackages"
      os: ubuntu-latest
      dotnet-version-matrix: '[{ "dotnet-version": "9.0.x", "framework": "net9.0" }]'
      dotnet-version: 9.0.x
      is-release-branch: false
      #is-release-branch: ${{ github.ref == 'refs/heads/main' }}
      #force-release: ${{ inputs.force-release }}
      force-release:: false
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
