name: example-pr

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: # 👈 manual trigger here to release - should only be on "release" workflows, not "pr" workflows
    inputs:
      force-release:
        description: "Force a release regardless of PR labels or branch"
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  dotnet-package-pr:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/dotnet-package-pr.yml
    with:
      working-directory: "./examples/NugetPackages"
      os: ubuntu-latest
      dotnet-version: 10.0.x
      is-release-branch: false # ${{ github.ref == 'refs/heads/main' }} for "release" workflows only
      # force-release: ${{ github.event.inputs.force-release || false }} for "release" workflows only
    secrets: inherit

  dotnet-minimal-web-api-pr:
    uses: ./.github/workflows/_dotnet-build-and-test.yml
    with:
      working-directory: "./examples/MinimalWebApi"
      os: "ubuntu-latest"
      dotnet-version: "10.0.x"
    secrets: inherit
