name: ci

on:
  pull_request:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  packages: write

jobs:
  # commitlint:
  #   name: Commitlint
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #     - run: npm install @commitlint/{config-conventional,cli}
  #     - uses: wagoid/commitlint-github-action@v6

  test:
    name: Test (SDK ${{ matrix.dotnet }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: ["8.0.x", "9.0.x"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore (locked)
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build -c Release --collect:"XPlat Code Coverage"

  pack_pr:
    name: Version, Pack, Publish PR preview
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Restore (locked)
        run: dotnet restore --locked-mode

      - name: Determine version (GitVersion)
        id: gitversion
        uses: gittools/actions/gitversion/execute@v2
        with:
          useConfigFile: true

      - name: Pack all projects
        run: |
          dotnet pack src/Package.Alpha/Package.Alpha.csproj -c Release -o ./artifacts \
            -p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
          dotnet pack src/Package.Bravo/Package.Bravo.csproj -c Release -o ./artifacts \
            -p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg

      - name: Publish to GitHub Packages (PR previews)
        run: |
          for f in artifacts/*.nupkg; do
            dotnet nuget push "$f" \
              --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              --api-key ${{ github.token }} \
              --skip-duplicate;
          done
