name: example-nuget-packages

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci-cd:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/_dotnet-build-test-pack-publish.yml
    with:
      working-directory: "./examples/NugetPackages"
      os: ubuntu-latest
      dotnet-version: 9.0.x
      is-release: false
      #is-release: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # build-and-test:
  #   uses: ./.github/workflows/_dotnet-build-and-test.yml
  #   with:
  #     working-directory: "./examples/NugetPackages"
  #     os-list: "ubuntu-latest"
  #     dotnet-version-list: "9.0.x"

  # get-version:
  #   uses: ./.github/workflows/_version.yml

  # pack:
  #   needs:
  #     - build-and-test
  #     - get-version
  #   uses: ./.github/workflows/_dotnet-build-and-pack.yml
  #   with:
  #     working-directory: "./examples/NugetPackages"
  #     package-version: ${{ needs.get-version.outputs.version }}
  #     package-artifact-name: "packages"
  #     add-assembly-version: false

  # publish:
  #   needs: pack
  #   permissions:
  #     contents: read
  #     packages: write
  #   uses: ./.github/workflows/_dotnet-publish-package.yml
  #   with:
  #     working-directory: "./examples/NugetPackages"
  #     package-artifact-name: "packages"
  #     upload-to-github: true
  #     upload-to-nuget: false
  #   secrets:
  #     GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
