name: pr

on:
  pull_request:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-labels:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/_pr-labeler.yml
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-lint:
    permissions:
      contents: read
    uses: ./.github/workflows/_pr-lint.yml
    with:
      validate-github-actions: true
      validate-yaml: true
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
