name: pr

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-labels:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/_pr-labeler.yml
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-lint:
    permissions:
      contents: read
    uses: ./.github/workflows/_pr-lint.yml
    with:
      run-lint: true
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
